[metadata]
addr = 0x154a
size = 0x546
last_change = 2023-03-06T18:59:43.709916Z

[header]
last_change = 2023-03-06T18:59:43.709916Z
name = "super_main"
addr = 0x154a

[stack_vars.-0xb8]
last_change = 2023-03-04T03:54:20.394228Z
offset = -184
name = "user_input"
type = "void *"
size = 0x8
addr = 0x154a

[stack_vars.-0xd8]
last_change = 2023-03-04T04:04:46.501965Z
offset = -216
name = "random_array"
type = "char *"
size = 0x8
addr = 0x154a

[stack_vars.-0xf2]
last_change = 2023-03-04T03:58:31.500531Z
offset = -242
name = "round_choice"
type = "char"
size = 0x1
addr = 0x154a

[stack_vars.-0xb0]
last_change = 2023-03-04T03:58:42.347928Z
offset = -176
name = "encrypted_flag"
type = "char *"
size = 0x8
addr = 0x154a
