[metadata]
addr = 0x154a
size = 0x546
last_change = 2023-03-04T03:58:00.953279Z

[stack_vars.-0xb8]
last_change = 2023-03-04T03:54:20.394228Z
offset = -184
name = "user_input"
type = "void *"
size = 0x8
addr = 0x154a

[stack_vars.-0xd8]
last_change = 2023-03-04T03:58:00.953279Z
offset = -216
name = "many_random_bytes"
type = "char *"
size = 0x8
addr = 0x154a
